query Posts {
  posts {
    data {
      id
      attributes {
        title
        slug
        content
        excerpt
        cover {
          data {
            attributes {
              name
              url
              alternativeText
            }
          }
        }
        published_date
      }
    }
  }
}
