query FetchPost($slug: String!) {
  posts(filters: { slug: { eq: $slug } }) {
    data {
      id
      attributes {
        title
        seo_title
        slug
        content
        excerpt
        difficulty {
          data {
            attributes {
              name
              slug
            }
          }
        }
        categories {
          data {
            attributes {
              slug
              name
            }
          }
        }
        cover {
          data {
            attributes {
              name
              alternativeText
              url
            }
          }
        }
        hide_cover_image
        published_date
        author {
          data {
            attributes {
              name
              position
            }
          }
        }
      }
    }
  }
}
