query FetchPost($slug: String!) {
  posts(filters: { slug: { eq: $slug } }) {
    data {
      id
      attributes {
        title
        slug
        content
        excerpt
        categories {
          data {
            attributes {
              slug
              name
            }
          }
        }
        cover {
          data {
            attributes {
              name
              alternativeText
              url
            }
          }
        }
        published_date
      }
    }
  }
}
